### ISSUE TITLE
How to use with Deluge?

### ISSUE THREAD

**Issue by SakhJack** [idlesign/torrt#43] opened 2019-05-15 17:52 UTC
I have all dependencies (python 3.7, Deluge, WebAPI plugin)
Do I install it somehow?
Do I use console command? If so, how do I start console?
Please provide noob friendly instructions
Your docs provide no such things besides for Transmission (Quickstart)
And even then, where do I enter `> torrt ...` commands?
Is it Windows or Python console?
I'm so confused please halp

**Comment by idlesign** [comment] 2019-05-16 03:29
Hi,

> I have all dependencies (python 3.7, Deluge, WebAPI plugin)

Deluge won't probably work on 3.7 (https://dev.deluge-torrent.org/ticket/1328). I suggest you moving to another client, since Deluge seems to have no updates in last 3 years or so.

> Do I install it somehow?

Installation process is descripbed in https://github.com/idlesign/torrt/blob/master/INSTALL

> Do I use console command? If so, how do I start console?

Docs https://torrt.readthedocs.io/en/latest/ mentions that ``torrt`` can function both as a console app, and Python module. On how to start a console (terminal) you need to consult your OS documentation.

> Please provide noob friendly instructions

Console apps assume that a user has some prior knowledge. Unfortunately it doesn't seem feasible to every app to describe how console commands work.

> Your docs provide no such things besides for Transmission (Quickstart)

This is because all RPC backends are configured in a similar fashion.

> And even then, where do I enter > torrt ... commands?

In a terminal.

> Is it Windows or Python console?

It is a terminal/console provided by your OS. For that matter Python REPL itself also runs in OS terminal.

_A sidenote: ``torrt`` is developed and used primarily on Linux, it may or may not work on Windows._

**Comment by SakhJack** [comment] 2019-05-16 11:53
I successfully configured rpc thorough localhost (it's on my machine)
But get stuck on rutracker setup, says "login with given credential failed, check your settings"
Password and login are correct, checked it manually

**Comment by ALTracer** [comment] 2019-05-16 16:31
Possible duplicate of #9
@SakhJack, what's in the .json file in the credentials properties? Encoding? Escaped?
Regarding domain name changes: consider submitting a pull request with names that work for you (with or without OpenNIC DNS, Tor, proxies etc.)

**Comment by idlesign** [comment] 2019-05-17 01:32
nnmclub alias is already known: https://github.com/idlesign/torrt/blob/ed90d84284dedf622a3f41a58b7a1079824e55d9/torrt/trackers/nnmclub.py#L16

**Comment by SakhJack** [comment] 2019-05-17 11:46
<details><summary>This is my config.json</summary><p>

```json
{
    "time_last_check": 0,
    "walk_interval_hours": 1,
    "rpc": {
        "transmission": {
            "url": "http://127.0.0.1:9091/transmission/rpc",
            "host": "127.0.0.1",
            "port": 9091,
            "user": null,
            "password": null,
            "enabled": true
        }
    },
    "trackers": {},
    "torrents": {},
    "notifiers": {},
    "bots": {}
}
```
</p></details>

or is it some other? 
If so where is it? (WIndows 10)
again I'm not really familiar with Python so don't assume I have same common sense
<details><summary>Full Debug log</summary>
<p>

```
DEBUG: Bootstrapping torrt environment ...
DEBUG: Importing RPC classes ...
DEBUG: Registering `deluge` from <class 'torrt.rpc.deluge.DelugeRPC'> ...
DEBUG: Registering `qbittorrent` from <class 'torrt.rpc.qbittorrent.QBittorrentRPC'> ...
DEBUG: Registering `transmission` from <class 'torrt.rpc.transmission.TransmissionRPC'> ...
DEBUG: Registering `utorrent` from <class 'torrt.rpc.utorrent.UTorrentRPC'> ...
DEBUG: Importing Tracker classes ...
DEBUG: Registering `tr.anidub.com` from <class 'torrt.trackers.anidub.AniDUBTracker'> ...
DEBUG: Registering `anilibria.tv` from <class 'torrt.trackers.anilibria.AnilibriaTracker'> ...
DEBUG: Registering `casstudio.tv` from <class 'torrt.trackers.casstudio.CasstudioTracker'> ...
DEBUG: Registering `kinozal.tv` from <class 'torrt.trackers.kinozal.KinozalTracker'> ...
DEBUG: Registering `nnm-club.me` from <class 'torrt.trackers.nnmclub.NNMClubTracker'> ...
DEBUG: Registering `rutor.org` from <class 'torrt.trackers.rutor.RutorTracker'> ...
DEBUG: Registering `rutracker.org` from <class 'torrt.trackers.rutracker.RuTrackerTracker'> ...
DEBUG: Importing Notifier classes ...
DEBUG: Registering `email` from <class 'torrt.notifiers.mail.EmailNotifier'> ...
DEBUG: Registering `telegram` from <class 'torrt.notifiers.telegram.TelegramNotifier'> ...
DEBUG: Importing Bot classes ...
DEBUG: Registering `telegram` from <class 'torrt.bots.telegram_bot.TelegramBot'> ...
DEBUG: Initializing objects registries from configuration file ...
DEBUG: Loading configuration file C:\Users\Gelus\.torrt\config.json ...
DEBUG: Spawning `TransmissionRPC` object with the given settings ...
DEBUG: Registering `transmission` from <torrt.rpc.transmission.TransmissionRPC object at 0x000001BA57B26EF0> ...
DEBUG: Spawning `AnilibriaTracker` object with the given settings ...
DEBUG: Registering `anilibria.tv` from <torrt.trackers.anilibria.AnilibriaTracker object at 0x000001BA57B18C50> ...
DEBUG: Spawning `RutorTracker` object with the given settings ...
DEBUG: Registering `rutor.org` from <torrt.trackers.rutor.RutorTracker object at 0x000001BA57B1F9B0> ...
INFO: Configuring `rutracker.org` tracker ...
DEBUG: Spawning `RuTrackerTracker` object with the given settings ...
DEBUG: Trying to login at https://rutracker.org/forum/login.php ...
DEBUG: Picking a mirror ...
DEBUG: Probing mirror: `https://rutracker.org` ...
DEBUG: Starting new HTTPS connection (1): rutracker.org:443
DEBUG: https://rutracker.org:443 "GET / HTTP/1.1" 301 178
DEBUG: https://rutracker.org:443 "GET /forum/index.php HTTP/1.1" 200 None
DEBUG: Fetching https://rutracker.org/forum/login.php ...
DEBUG: Starting new HTTPS connection (1): rutracker.org:443
DEBUG: https://rutracker.org:443 "POST /forum/login.php HTTP/1.1" 200 None
WARNING: Login with given credentials failed
ERROR: Tracker `rutracker.org` configuration failed. Check your settings
```
</p></details>

**Comment by idlesign** [comment] 2019-05-17 11:54
> This is my config.json

It seems that tracker is not configured (see empty `trackers` clause) — no credentials given.

**Comment by SakhJack** [comment] 2019-05-17 12:11
Of course It's not configured, because that's where I get stuck, that's the issue I am dealing with...
clause where? API? this repo? please be more specific
Am I suppose to manually edit that json? What is the structure of this json?
Again please provide detailed answers I do not have same knowledge as a user

**Comment by idlesign** [comment] 2019-05-17 12:53
You don't need to edit the config manually, credentials will be populated on successful configuration (using `torrt configure_tracker` command as per docs). `trackers` clause in `config.json` having no information on credentials indicates configuration problems (ALTracer's comment on config contents may be somewhat misleading, cause it supposed you've already configured the tracker and now just having a torrent synchronization problem).

> my password is 20 characters long, with random characters like (%$,*), I put password in quotes to bypass, if that matters

It may matter. Please consult Windows console documentation on command arguments escaping.
You may also try to configure other trackers (maybe with simplier passwords, not requiring escapes), just to see how that works.

> P.S. is it always this hard to troubleshoot python software for casual user??

Your situation has nothing to do with "python software". May I remind you that this issue started with installation and terminal usage related questions covered in docs that can be found within the package and around the network. Now it further developed into a system software (firewall) and a tracker configuration issue.

And once again: I have not tested `torrt` on Windows.

**Comment by SakhJack** [comment] 2019-05-17 13:22
Okay, so it was reserved characters issue

I changed password to simple letters/numbers and it worked

Just have to figure out how to escape properly in Windows console

Sorry for my frustration

Last question: how exactly does it perform scheduled auto-updates? Does it run in the background of OS or Torrent client? Does Torrent client need to be running at the time of `walk`?

**Comment by idlesign** [comment] 2019-05-17 13:42
> you might want to add that as tip in docs

Pull request with docs update for Windows is welcome.

> Does it run in the background of OS (Task Schedule) or Torrent client?

You just run `torrt walk` using any scheduler (Windown should have one built-in, I expect) in intervals as you consider fit.

> Does Torrent client need to be running at the time of walk?

Yes, because it (client, e.g. Transmission) provides an API which `torrt` uses. Client will handle downloading an seeding in background. It's convenient to place such a client on NAS or on a router with HDD or something

**Closed** 2019-05-17 16:41 UTC
Labels: question
